"""Launch a paired arm the standard way: clean worktree, lineup runners, optional queueing.

Every arm since 2026-09-16 has been run by hand-copied ``run_group.py`` /
``queue.sh`` pairs under ``artifacts/<root>/launch/``; this is that pattern
as a tool. It

- checks the main tree is clean (provenance must say ``dirty: false``);
- adds a detached git worktree at ``--commit`` (default HEAD) and copies
  ``.env`` into it, so the worktree stays clean too;
- writes ``artifacts/<root>/launch/run_group.py`` (one process per lineup
  group, five two-seed chunks each, mirroring the ``rr_belief_opp``
  baseline so every (lineup, rotation, seed) game pairs) and
  ``queue.sh`` (waits for ``--after`` roots to finish, then starts the
  runners), and starts the queue in the background;
- **reaps its own worktree** once every runner group reports
  ``GROUP COMPLETE``. This used to be a printed reminder to run
  ``git worktree remove`` by hand, which was missed 7 times out of 9 and left
  seven stale checkouts sitting beside the repo looking like duplicated
  projects. ``--prune`` cleans up the ones whose queue died before reaping.

Nothing of value lives in a worktree: the runners write every artifact to
``MAIN/artifacts/<root>``, and the worktree holds only source at the pinned
commit. It exists so an arm's code is frozen while the main tree keeps moving --
provenance has to say ``dirty: false``, and arms run for hours.

Two-player arms use the four standard lineup groups. ``--player-count 3``
runs one process per pair of opponents from the same roster, all three
rotations, ``--seeds`` seeds. ``--mirror`` puts ``potential_points`` in every
seat (``docs/experiments/self_play_opponent_plan.md``): ``--seeds`` split over
``--runners`` processes, every rotation, and ``--study-search`` gives lineup
position 1 its own search config (read with ``arm_contrast --agent
potential_points@1``).

    python analysis/launch_arm.py rr_prod_5s \\
        --search '{"max_decision_time_ms": 5000, "search_prerank": "beam_leaf"}' \\
        --after rr3p_opp/launch/oracle:6
    python analysis/launch_arm.py rr_opener_v4 \\
        --setup-override potential_points=potential_points_setup_v3
    python analysis/launch_arm.py rr3p_belief --player-count 3 \\
        --search '{"search_opponent_model": "belief"}'
    python analysis/launch_arm.py mirror_2p --mirror --seeds 1-40 --runners 4
    python analysis/launch_arm.py --prune            # remove finished worktrees
    python analysis/launch_arm.py --prune --dry-run  # say what it would remove
    python analysis/launch_arm.py mirror_2p_greedy --mirror --seeds 1-40 --runners 4 \\
        --study-search '{"search_opponent_model": "greedy"}' --after mirror_2p:4

Read the result with ``analysis/arm_contrast.py --baseline artifacts/rr_belief_opp
--arm artifacts/<root>`` and ``analysis/decision_profile_report.py artifacts/<root>
--value-against artifacts/rr_belief_opp``.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

MAIN = Path(__file__).resolve().parents[1]
OPPONENTS = (
    "archetype_engine_builder",
    "archetype_bonus_card_focus",
    "net_value_response",
    "greedy_immediate",
)
GROUPS_2P = {
    "grepot": ["greedy_immediate", "potential_points"],
    "poteng": ["potential_points", "archetype_engine_builder"],
    "potbon": ["potential_points", "archetype_bonus_card_focus"],
    "potnet": ["potential_points", "net_value_response"],
}

RUN_GROUP_2P = '''"""{description}

Generated by analysis/launch_arm.py. One lineup group, five two-seed chunks,
mirroring the rr_belief_opp baseline so every (lineup, rotation, seed) pairs.
"""

import sys
import time

from flows.round_robin import run_round_robin
from wingspan_ai.agents.potential_points import PotentialPointsSearchConfig

MAIN = {main!r}
GROUPS = {groups!r}
group = sys.argv[1]
for low in (1, 3, 5, 7, 9):
    label = f"{root}_{{group}}_s{{low}}_{{low + 1}}"
    started = time.time()
    print(f"[{{group}}] start {{label}}", flush=True)
    summary = run_round_robin(
        workbook_path=f"{{MAIN}}/data/raw/wingspan-card-list.xlsx",
        seeds=[low, low + 1],
        roster=GROUPS[group],
        setup_policy_kinds=["control"],
        artifact_root=f"{{MAIN}}/artifacts/{root}",
        batch_label=label,
        potential_points_search=PotentialPointsSearchConfig(**{search!r}),
        setup_policy_overrides={overrides!r},
    )
    print(f"[{{group}}] done {{label}}: {{summary['total_games']}} games in "
          f"{{time.time() - started:.0f}}s provenance={{summary['code_provenance']}}", flush=True)
print(f"[{{group}}] GROUP COMPLETE", flush=True)
'''

RUN_GROUP_3P = '''"""{description}

Generated by analysis/launch_arm.py. One three-player lineup (potential_points
plus two opponents), all three rotations, seeds {seeds!r}.
"""

import sys
import time

from flows.round_robin import run_round_robin
from wingspan_ai.agents.potential_points import PotentialPointsSearchConfig

MAIN = {main!r}
opp_a, opp_b = sys.argv[1:3]
label = f"{root}_{{opp_a.removeprefix('archetype_')}}_{{opp_b.removeprefix('archetype_')}}"
started = time.time()
print(f"[{{label}}] start", flush=True)
summary = run_round_robin(
    workbook_path=f"{{MAIN}}/data/raw/wingspan-card-list.xlsx",
    seeds={seeds!r},
    roster=["potential_points", opp_a, opp_b],
    setup_policy_kinds=["control"],
    artifact_root=f"{{MAIN}}/artifacts/{root}",
    batch_label=label,
    player_count=3,
    potential_points_search=PotentialPointsSearchConfig(**{search!r}),
    setup_policy_overrides={overrides!r},
)
print(f"[{{label}}] done: {{summary['total_games']}} games in {{time.time() - started:.0f}}s "
      f"provenance={{summary['code_provenance']}}", flush=True)
print(f"[{{label}}] GROUP COMPLETE", flush=True)
'''

RUN_GROUP_MIRROR = '''"""{description}

Generated by analysis/launch_arm.py. A mirror match: potential_points in
every seat, every rotation, one seed chunk per process. Position 1 is the
study seat when a study search is given.
"""

import sys
import time

from flows.round_robin import run_round_robin
from wingspan_ai.agents.potential_points import PotentialPointsSearchConfig

MAIN = {main!r}
seeds = [int(s) for s in sys.argv[1].split(",")]
label = f"{root}_s{{seeds[0]}}_{{seeds[-1]}}"
search = {search!r}
study = {study!r}
by_position = None
if study is not None:
    by_position = {{1: PotentialPointsSearchConfig(**{{**search, **study}})}}
started = time.time()
print(f"[{{label}}] start", flush=True)
summary = run_round_robin(
    workbook_path=f"{{MAIN}}/data/raw/wingspan-card-list.xlsx",
    seeds=seeds,
    roster=["potential_points"] * {player_count},
    setup_policy_kinds=["control"],
    artifact_root=f"{{MAIN}}/artifacts/{root}",
    batch_label=label,
    player_count={player_count},
    potential_points_search=PotentialPointsSearchConfig(**search),
    potential_points_search_by_position=by_position,
    setup_policy_overrides={overrides!r},
)
print(f"[{{label}}] done: {{summary['total_games']}} games in {{time.time() - started:.0f}}s "
      f"provenance={{summary['code_provenance']}}", flush=True)
print(f"[{{label}}] GROUP COMPLETE", flush=True)
'''

QUEUE = """#!/bin/zsh
# Generated by analysis/launch_arm.py for {root}.
MAIN={main}
WT={worktree}
export WINGSPAN_CARD_WORKBOOK="$MAIN/data/raw/wingspan-card-list.xlsx"
export PREFECT_HOME="$MAIN/.prefect"
export PYTHONPATH="$WT/src:$WT"
wait_for() {{
  until [ "$(grep -l 'GROUP COMPLETE' $1/*.log 2>/dev/null | wc -l | tr -d ' ')" = "$2" ]; do
    sleep 60
  done
}}
{waits}
cd "$WT" || exit 1
{launches}
echo "$(date) launched {root}" >> "$MAIN/artifacts/{root}/launch/queue.log"
wait_for "$MAIN/artifacts/{root}/launch" {runner_count}
echo "$(date) finished {root}" >> "$MAIN/artifacts/{root}/launch/queue.log"
# Reap the worktree. Every group has printed GROUP COMPLETE by here, but that is
# the last line of run_group.py rather than proof the process has exited, so wait
# for the processes to go before pulling the checkout out from under them.
for _ in 1 2 3 4 5 6 7 8 9 10; do
  pgrep -f "artifacts/{root}/launch/run_group.py" >/dev/null || break
  sleep 6
done
cd "$MAIN" || exit 1
if git worktree remove "$WT" 2>/dev/null; then
  echo "$(date) reaped worktree $WT" >> "$MAIN/artifacts/{root}/launch/queue.log"
else
  echo "$(date) worktree $WT left in place; run 'python analysis/launch_arm.py --prune'" \
    >> "$MAIN/artifacts/{root}/launch/queue.log"
fi
"""


def _parse_seeds(text: str) -> list[int]:
    if "-" in text and "," not in text:
        low, high = text.split("-", 1)
        return list(range(int(low), int(high) + 1))
    return [int(s) for s in text.split(",")]


def git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], cwd=MAIN, check=True, capture_output=True, text=True
    ).stdout


def arm_worktrees() -> list[tuple[Path, str]]:
    """``(path, root)`` for every arm worktree this launcher created."""

    prefix = f"{MAIN.name}-arm-"
    out: list[tuple[Path, str]] = []
    for line in git("worktree", "list", "--porcelain").splitlines():
        if not line.startswith("worktree "):
            continue
        path = Path(line.removeprefix("worktree ").strip())
        if path != MAIN and path.name.startswith(prefix):
            out.append((path, path.name.removeprefix(prefix)))
    return out


def arm_is_running(root: str) -> bool:
    patterns = (f"artifacts/{root}/launch/run_group.py", f"artifacts/{root}/launch/queue.sh")
    return any(
        subprocess.run(["pgrep", "-f", pattern], capture_output=True).returncode == 0
        for pattern in patterns
    )


def arm_is_complete(root: str) -> bool:
    """Every runner group printed GROUP COMPLETE.

    The same marker ``queue.sh`` waits on, so this agrees with the queue's own
    notion of done rather than inventing a second one.
    """

    launch = MAIN / "artifacts" / root / "launch"
    skip = {"queue.log", "queue_runner.log"}
    logs = [path for path in launch.glob("*.log") if path.name not in skip]
    return bool(logs) and all("GROUP COMPLETE" in path.read_text(errors="ignore") for path in logs)


def prune_worktrees(dry_run: bool = False) -> int:
    """Remove arm worktrees whose arms are finished.

    The launcher has printed "remove the worktree when the arm is done" since it
    was written and that reminder was missed 7 times out of 9, so the queue now
    reaps its own worktree and this cleans up the ones whose queue died first.
    ``git worktree remove`` refuses a dirty worktree, which is the safety net:
    nothing with uncommitted work is removed here.
    """

    worktrees = arm_worktrees()
    if not worktrees:
        print("no arm worktrees")
        return 0
    removed = kept = 0
    for path, root in worktrees:
        if arm_is_running(root):
            print(f"  keep   {path.name}: still running")
            kept += 1
            continue
        if not arm_is_complete(root):
            print(f"  keep   {path.name}: no GROUP COMPLETE in every runner log")
            kept += 1
            continue
        if dry_run:
            print(f"  would remove {path.name}")
            removed += 1
            continue
        try:
            git("worktree", "remove", str(path))
            print(f"  removed {path.name}")
            removed += 1
        except subprocess.CalledProcessError as error:
            detail = (error.stderr or "").strip().splitlines()
            print(f"  keep   {path.name}: {detail[-1] if detail else 'removal refused'}")
            kept += 1
    print(f"{removed} {'would be removed' if dry_run else 'removed'}, {kept} kept")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "root", nargs="?", help="artifact root name under artifacts/, e.g. rr_prod_5s"
    )
    parser.add_argument(
        "--prune",
        action="store_true",
        help="remove arm worktrees whose arms are finished, then exit",
    )
    parser.add_argument("--commit", default="HEAD")
    parser.add_argument(
        "--search", default="{}", help="JSON kwargs for PotentialPointsSearchConfig"
    )
    parser.add_argument(
        "--setup-override",
        action="append",
        default=[],
        metavar="AGENT=POLICY",
        help="setup_policy_overrides entry, e.g. potential_points=potential_points_setup_v3_keep3",
    )
    parser.add_argument("--player-count", type=int, default=2, choices=(2, 3))
    parser.add_argument(
        "--opponent-pairs",
        default=None,
        help="3p only: restrict the lineups to these opponent pairs, comma separated, "
        "each as 'opponent_a+opponent_b'. Fewer pairs on more seeds is how a 3p arm "
        "gets decks instead of games (results_ledger.md, 'Decks, not games').",
    )
    parser.add_argument(
        "--seeds",
        default="1,2,3,4,5",
        help="3p and mirror arms; comma list or a-b range (2p roster arms always use seeds 1-10)",
    )
    parser.add_argument(
        "--mirror", action="store_true", help="potential_points in every seat (self-play)"
    )
    parser.add_argument("--runners", type=int, default=4, help="mirror: seed chunks / processes")
    parser.add_argument(
        "--study-search",
        default=None,
        help="mirror: JSON kwargs overriding --search for lineup position 1 (the study seat)",
    )
    parser.add_argument(
        "--after",
        action="append",
        default=[],
        metavar="ROOT[/subdir]:N",
        help="wait for N 'GROUP COMPLETE' logs under artifacts/ROOT/launch[/subdir] first",
    )
    parser.add_argument("--description", default="")
    parser.add_argument("--dry-run", action="store_true", help="write the scripts, do not start")
    args = parser.parse_args(argv)

    if args.prune:
        return prune_worktrees(dry_run=args.dry_run)
    if not args.root:
        parser.error("root is required unless --prune is passed")
    if not args.dry_run and git("status", "--porcelain").strip():
        print("main tree is dirty; commit or stash first (provenance must say dirty: false)")
        return 1
    search = json.loads(args.search)
    study = json.loads(args.study_search) if args.study_search else None
    overrides = dict(item.split("=", 1) for item in args.setup_override) or None
    commit = git("rev-parse", "--short", args.commit).strip()
    worktree = MAIN.parent / f"{MAIN.name}-arm-{args.root}"
    if worktree.exists():
        print(f"{worktree} exists; remove it first (git worktree remove)")
        return 1
    launch = MAIN / "artifacts" / args.root / "launch"
    launch.mkdir(parents=True, exist_ok=True)
    description = args.description or f"{args.root}: search={search} overrides={overrides}"

    if args.mirror:
        seeds = _parse_seeds(args.seeds)
        chunks = [seeds[i :: args.runners] for i in range(args.runners)]
        chunks = [sorted(chunk) for chunk in chunks if chunk]
        script = RUN_GROUP_MIRROR.format(
            description=description,
            main=str(MAIN),
            root=args.root,
            player_count=args.player_count,
            search=search,
            study=study,
            overrides=overrides,
        )
        launches = "\n".join(
            f'nohup "$MAIN/.venv/bin/python" "$MAIN/artifacts/{args.root}/launch/run_group.py" '
            f"{','.join(str(s) for s in chunk)} "
            f'> "$MAIN/artifacts/{args.root}/launch/chunk{i}.log" 2>&1 &'
            for i, chunk in enumerate(chunks)
        )
        runner_count = len(chunks)
    elif args.player_count == 2:
        script = RUN_GROUP_2P.format(
            description=description,
            main=str(MAIN),
            groups=GROUPS_2P,
            root=args.root,
            search=search,
            overrides=overrides,
        )
        launches = "\n".join(
            f'nohup "$MAIN/.venv/bin/python" "$MAIN/artifacts/{args.root}/launch/run_group.py" {g} '
            f'> "$MAIN/artifacts/{args.root}/launch/{g}.log" 2>&1 &'
            for g in GROUPS_2P
        )
        runner_count = len(GROUPS_2P)
    else:
        seeds = _parse_seeds(args.seeds)
        script = RUN_GROUP_3P.format(
            description=description,
            main=str(MAIN),
            root=args.root,
            seeds=seeds,
            search=search,
            overrides=overrides,
        )
        if args.opponent_pairs:
            pairs = []
            for item in args.opponent_pairs.split(","):
                first, _, second = item.strip().partition("+")
                if first not in OPPONENTS or second not in OPPONENTS:
                    print(f"unknown opponent pair {item!r}; expected two of {OPPONENTS}")
                    return 1
                pairs.append((first, second))
        else:
            pairs = [(a, b) for i, a in enumerate(OPPONENTS) for b in OPPONENTS[i + 1 :]]
        launches = "\n".join(
            f'nohup "$MAIN/.venv/bin/python" "$MAIN/artifacts/{args.root}/launch/run_group.py" '
            f'{a} {b} > "$MAIN/artifacts/{args.root}/launch/{a}_{b}.log" 2>&1 &'
            for a, b in pairs
        )
        runner_count = len(pairs)
    (launch / "run_group.py").write_text(script)

    waits = []
    for item in args.after:
        path, _, count = item.rpartition(":")
        if not path:
            path, count = item, "4"
        root_dir, _, sub = path.partition("/")
        waits.append(
            f'wait_for "$MAIN/artifacts/{root_dir}/launch{"/" + sub if sub else ""}" {count}'
        )
    queue = QUEUE.format(
        root=args.root,
        main=str(MAIN),
        worktree=str(worktree),
        waits="\n".join(waits),
        launches=launches,
        runner_count=runner_count,
    )
    (launch / "queue.sh").write_text(queue)
    os.chmod(launch / "queue.sh", 0o755)
    (launch / "arm.json").write_text(
        json.dumps(
            {
                "root": args.root,
                "commit": commit,
                "search": search,
                "study_search": study,
                "mirror": args.mirror,
                "opponent_pairs": args.opponent_pairs,
                "overrides": overrides,
                "player_count": args.player_count,
                "after": args.after,
                "description": description,
            },
            indent=2,
        )
        + "\n"
    )
    if args.dry_run:
        print(
            f"wrote {launch}/run_group.py, queue.sh, arm.json (dry run; no worktree, not started)"
        )
        return 0

    git("worktree", "add", "--detach", str(worktree), commit)
    if (MAIN / ".env").exists():
        shutil.copy(MAIN / ".env", worktree / ".env")
    if subprocess.run(
        ["git", "status", "--porcelain"], cwd=worktree, capture_output=True, text=True
    ).stdout.strip():
        print("worktree is dirty after setup; aborting")
        return 1
    subprocess.Popen(
        ["/bin/zsh", str(launch / "queue.sh")],
        stdout=(launch / "queue_runner.log").open("w"),
        stderr=subprocess.STDOUT,
        start_new_session=True,
    )
    print(
        f"{args.root}: worktree {worktree} at {commit}; queue started"
        + (f" (after {', '.join(args.after)})" if args.after else "")
    )
    print(f"remove the worktree when the arm is done: git worktree remove {worktree}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
